USE SchoolDB;

CREATE TABLE People (
	AccountId INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
	Password NVARCHAR(50) NOT NULL
)
GO

CREATE TABLE Teachers (
	TeacherId INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
	FirstName NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(50) NOT NULL,
	Gender NVARCHAR(1) NOT NULL,
	PhoneNumber VARCHAR(9) NOT NULL,
	Pesel VARCHAR(11) NOT NULL UNIQUE,
	AccountId INTEGER NOT NULL,
	CONSTRAINT TeachersFK FOREIGN KEY(AccountId) REFERENCES People(AccountID)
	ON UPDATE CASCADE
	ON DELETE CASCADE
)
GO
CREATE TABLE Classes (
	ClassId INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
	ClassLabel NVARCHAR(2) NOT NULL,
	HeadTeacherID INTEGER NOT NULL,
	CONSTRAINT HeadTeacherFK FOREIGN KEY (HeadTeacherId) REFERENCES Teachers(TeacherId)
)


CREATE TABLE Students(
	StudentId INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
    FirstName NVARCHAR(50) NOT NULL,
    LastName NVARCHAR(50) NOT NULL,
	ClassId INTEGER NOT NULL,
	AccountId INTEGER NOT NULL,
    CONSTRAINT StudentsAcFK FOREIGN KEY(AccountId) REFERENCES People(AccountId)
	ON UPDATE CASCADE
    ON DELETE CASCADE,
	CONSTRAINT StudentClassFK FOREIGN KEY(ClassId) REFERENCES Classes(ClassId)
)

CREATE TABLE StudentsDetails(
	StudentId INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
	BirthDate DATE NOT NULL,
    Gender NVARCHAR(1) NOT NULL,
    PhoneNumber VARCHAR(9) NOT NULL,
	Pesel VARCHAR(11) NOT NULL UNIQUE,
	AccountId Integer NOT NULL,
	CONSTRAINT StudentsFK FOREIGN KEY(AccountId) REFERENCES People(AccountId)
	ON UPDATE CASCADE
    ON DELETE CASCADE
)

CREATE TABLE Classrooms (
	ClassroomID INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
	ClassroomName NVARCHAR(50) NOT NULL
)

CREATE TABLE Lessons (
	LessonID INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
	LessonName NVARCHAR(50) NOT NULL,
    LessonDay NVARCHAR(9),
	LessonStart TIME NOT NULL,
	LessonEnd TIME NOT NULL,
	LessonTeacher INTEGER NOT NULL,
	Classroom INTEGER NOT NULL,
	CONSTRAINT TeacherFK FOREIGN KEY(LessonTeacher) REFERENCES Teachers(TeacherID),
	CONSTRAINT ClasroomFK FOREIGN KEY(Classroom) REFERENCES Classrooms(ClassroomID)
)

CREATE TABLE ExtraLessons (
	ExtraLessonID INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
	LessonName NVARCHAR(50) NOT NULL,
	LessonStart TIME NOT NULL,
	LessonEnd TIME NOT NULL,
	LessonTeacher INTEGER NOT NULL,
	Classroom INTEGER NOT NULL,
	CONSTRAINT TeacherEFK FOREIGN KEY(LessonTeacher) REFERENCES Teachers(TeacherID),
	CONSTRAINT ClasroomEFK FOREIGN KEY(Classroom) REFERENCES Classrooms(ClassroomID)
)

CREATE TABLE Grades(
	GradeId INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
    StudentId INTEGER NOT NULL,
    TeacherId INTEGER NOT NULL,
    Grade FLOAT,
    Date DATE NOT NULL,
    Type NVARCHAR(50),
    CONSTRAINT StudentGradeFK FOREIGN KEY(StudentId) REFERENCES Students(StudentId),
    CONSTRAINT TeacherGradeFK FOREIGN KEY(TeacherId) REFERENCES Teachers(TeacherId)
)

CREATE TABLE Absences (
    AbsenceId INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
    StudentId INTEGER NOT NULL,
    Date DATE NOT NULL,
    Status NVARCHAR(1) NOT NULL,
    CONSTRAINT AbsentStudentFK FOREIGN KEY(StudentId) REFERENCES Students(StudentId)
    ON UPDATE CASCADE
    ON DELETE CASCADE
)

CREATE TABLE Notes (
    NoteId INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
    TeacherId INTEGER NOT NULL,
    StudentId INTEGER NOT NULL,
    Date DATE NOT NULL,
    Description NVARCHAR(150) NOT NULL,
    CONSTRAINT NotingTeacherId FOREIGN KEY(TeacherId) REFERENCES Teachers(TeacherId),
    CONSTRAINT NotedStudentId FOREIGN KEY(StudentId) REFERENCES Students(StudentId)
)

CREATE TABLE Exams (
    ExamId INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
    ClassId INTEGER NOT NULL,
    LessonId INTEGER NOT NULL,
    ExamDate DATE NOT NULL,
    CONSTRAINT ExamsFK FOREIGN KEY(ClassId) REFERENCES Classes(ClassId),
    CONSTRAINT CourseFK FOREIGN KEY(LessonId) REFERENCES Lessons(LessonId)
)

CREATE TABLE ExamResults (
    ExamId INTEGER NOT NULL,
    StudentId INTEGER NOT NULL,
    Grade FLOAT NOT NULL,
    ResultDate DATE NOT NULL,
	CONSTRAINT ExamResultsPK PRIMARY KEY(ExamId, StudentId),
    CONSTRAINT ExamsResultsFK FOREIGN KEY(ExamId) REFERENCES Exams(ExamId),
)

CREATE TABLE Authors (
    AuthorId INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
    Name NVARCHAR(50) NOT NULL,
    Surname NVARCHAR(50) NOT NULL,
)

CREATE TABLE Books (
    BookId INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
    AuthorId INTEGER NOT NULL,
    Title NVARCHAR(50) NOT NULL,
    Amount INTEGER NOT NULL,
    Category NVARCHAR(50) NOT NULL,
    CONSTRAINT AuthorFK FOREIGN KEY(AuthorId) REFERENCES Authors(AuthorId)
)

CREATE TABLE Borrows (
    BorrowId INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
    StudentId INTEGER NOT NULL,
    BookId INTEGER NOT NULL,
    TakenDate DATE NOT NULL,
    ReturnDate DATE,
    CONSTRAINT BookFK FOREIGN KEY(BookId) REFERENCES Books(BookId),
    CONSTRAINT StudentBorrowsFK FOREIGN KEY(StudentId) REFERENCES Students(StudentId)
)
