USE SchoolDB;

IF OBJECT_ID('Absences', 'U') IS NOT NULL DROP TABLE Absences 
IF OBJECT_ID('Borrows', 'U') IS NOT NULL DROP TABLE Borrows 
IF OBJECT_ID('Notes', 'U') IS NOT NULL DROP TABLE Notes 
IF OBJECT_ID('Books', 'U') IS NOT NULL DROP TABLE Books
IF OBJECT_ID('Authors', 'U') IS NOT NULL DROP TABLE Authors
IF OBJECT_ID('Grades', 'U') IS NOT NULL DROP TABLE Grades 
IF OBJECT_ID('ExamResults', 'U') IS NOT NULL DROP TABLE ExamResults 
IF OBJECT_ID('Exams', 'U') IS NOT NULL DROP TABLE Exams
IF OBJECT_ID('ExtraLessons', 'U') IS NOT NULL DROP TABLE ExtraLessons 
IF OBJECT_ID('Lessons', 'U') IS NOT NULL DROP TABLE Lessons
IF OBJECT_ID('Classrooms', 'U') IS NOT NULL DROP TABLE Classrooms
IF OBJECT_ID('Students', 'U') IS NOT NULL DROP TABLE Students
IF OBJECT_ID('StudentsDetails', 'U') IS NOT NULL DROP TABLE StudentsDetails 
IF OBJECT_ID('Classes', 'U') IS NOT NULL DROP TABLE Classes
IF OBJECT_ID('Teachers', 'U') IS NOT NULL DROP TABLE Teachers
IF OBJECT_ID('People', 'U') IS NOT NULL DROP TABLE People 
GO

CREATE TABLE People (
	AccountId INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
	Password NVARCHAR(50) NOT NULL
    CONSTRAINT password_length CHECK(LEN(Password) >= 5)
)
GO

CREATE TABLE Teachers (
	TeacherId INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
	FirstName NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(50) NOT NULL,
	Gender NVARCHAR(1) NOT NULL,
	PhoneNumber VARCHAR(9) NOT NULL,
	Pesel VARCHAR(11) NOT NULL UNIQUE,
	AccountId INTEGER NOT NULL UNIQUE,
	CONSTRAINT TeachersFK FOREIGN KEY(AccountId) REFERENCES People(AccountID)
	ON UPDATE CASCADE
	ON DELETE CASCADE,
    CONSTRAINT phone_valid CHECK(ISNUMERIC(PhoneNumber) = 1 AND LEN(PhoneNumber) = 9),
    CONSTRAINT pesel_valid CHECK(ISNUMERIC(Pesel) = 1 AND LEN(Pesel) = 11)
)
GO

CREATE TABLE Classes (
	ClassId INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
	ClassLabel NVARCHAR(2) NOT NULL,
	HeadTeacherId INTEGER NOT NULL,
	CONSTRAINT HeadTeacherFK FOREIGN KEY (HeadTeacherId) REFERENCES Teachers(TeacherId)
)
GO 

CREATE TABLE Students(
	StudentId INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
    FirstName NVARCHAR(50) NOT NULL,
    LastName NVARCHAR(50) NOT NULL,
	ClassId INTEGER NOT NULL,
	AccountId INTEGER NOT NULL UNIQUE,
    CONSTRAINT StudentsAcFK FOREIGN KEY(AccountId) REFERENCES People(AccountId)
	ON UPDATE CASCADE
    ON DELETE CASCADE,
	CONSTRAINT StudentClassFK FOREIGN KEY(ClassId) REFERENCES Classes(ClassId)
)
GO

CREATE TABLE StudentsDetails(
	StudentId INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
	BirthDate DATE NOT NULL,
    Gender NVARCHAR(1) NOT NULL,
    PhoneNumber VARCHAR(9) NOT NULL,
	Pesel VARCHAR(11) NOT NULL UNIQUE,
	AccountId Integer NOT NULL UNIQUE,
	CONSTRAINT StudentsFK FOREIGN KEY(AccountId) REFERENCES People(AccountId)
	ON UPDATE CASCADE
    ON DELETE CASCADE,
    CONSTRAINT student_phone_valid CHECK(ISNUMERIC(PhoneNumber) = 1 AND LEN(PhoneNumber) = 9),
    CONSTRAINT student_pesel_valid CHECK(ISNUMERIC(Pesel) = 1 AND LEN(Pesel) = 11)
)
GO

CREATE TABLE Classrooms (
	ClassroomId INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
	ClassroomName NVARCHAR(50) NOT NULL
)
GO

CREATE TABLE Lessons (
	LessonID INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
	LessonName NVARCHAR(50) NOT NULL,
    LessonDay NVARCHAR(20),
	LessonStart TIME NOT NULL,
	LessonEnd TIME NOT NULL,
    LessonClass INT NOT NULL,
	LessonTeacher INTEGER NOT NULL,
	Classroom INTEGER NOT NULL,
    CONSTRAINT ClassFK FOREIGN KEY(LessonClass) REFERENCES Classes(ClassId),
	CONSTRAINT TeacherFK FOREIGN KEY(LessonTeacher) REFERENCES Teachers(TeacherId),
	CONSTRAINT ClasroomFK FOREIGN KEY(Classroom) REFERENCES Classrooms(ClassroomID)
)
GO

CREATE TABLE ExtraLessons (
	ExtraLessonID INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
	LessonName NVARCHAR(50) NOT NULL,
    LessonDay NVARCHAR(20),
	LessonStart TIME NOT NULL,
	LessonEnd TIME NOT NULL,
	LessonTeacher INTEGER NOT NULL,
    LessonClass INT NOT NULL,
	Classroom INTEGER NOT NULL,
    CONSTRAINT ClassEFK FOREIGN KEY(LessonClass) REFERENCES Classes(ClassId),
	CONSTRAINT TeacherEFK FOREIGN KEY(LessonTeacher) REFERENCES Teachers(TeacherId),
	CONSTRAINT ClassroomEFK FOREIGN KEY(Classroom) REFERENCES Classrooms(ClassroomId)
)
GO

CREATE TABLE Grades(
	GradeId INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
    StudentId INTEGER NOT NULL,
    TeacherId INTEGER NOT NULL,
    GradeLesson NVARCHAR(20) NOT NULL,
    Grade FLOAT NOT NULL,
    Date DATE NOT NULL,
    Type NVARCHAR(50),
    CONSTRAINT StudentGradeFK FOREIGN KEY(StudentId) REFERENCES Students(StudentId),
    CONSTRAINT TeacherGradeFK FOREIGN KEY(TeacherId) REFERENCES Teachers(TeacherId),
    CONSTRAINT grade_valid CHECK(Grade BETWEEN 1 AND 6)
)
GO

CREATE TABLE Absences (
    AbsenceId INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
    StudentId INTEGER NOT NULL,
    Date DATE NOT NULL,
    Status NVARCHAR(1) NOT NULL,
    CONSTRAINT AbsentStudentFK FOREIGN KEY(StudentId) REFERENCES Students(StudentId)
    ON UPDATE CASCADE
    ON DELETE CASCADE
)
GO

CREATE TABLE Notes(
    NoteId INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
    TeacherId INTEGER NOT NULL,
    StudentId INTEGER NOT NULL,
    Date DATE NOT NULL,
    Description NVARCHAR(150) NOT NULL,
    CONSTRAINT NotingTeacherId FOREIGN KEY(TeacherId) REFERENCES Teachers(TeacherId),
    CONSTRAINT NotedStudentId FOREIGN KEY(StudentId) REFERENCES Students(StudentId)
)
GO

CREATE TABLE Exams (
    ExamId INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
    ClassId INTEGER NOT NULL,
    LessonId INTEGER NOT NULL,
    ExamDate DATE NOT NULL,
    CONSTRAINT ExamsFK FOREIGN KEY(ClassId) REFERENCES Classes(ClassId),
    CONSTRAINT CourseFK FOREIGN KEY(LessonId) REFERENCES Lessons(LessonId)
)
GO

CREATE TABLE ExamResults (
    ExamId INTEGER NOT NULL,
    StudentId INTEGER NOT NULL,
    Grade FLOAT NOT NULL,
    ResultDate DATE NOT NULL,
	CONSTRAINT ExamResultsPK PRIMARY KEY(ExamId, StudentId),
    CONSTRAINT ExamsResultsFK FOREIGN KEY(ExamId) REFERENCES Exams(ExamId),
    CONSTRAINT exam_grade_valid CHECK(Grade BETWEEN 1 AND 6)
)
GO

CREATE TABLE Authors (
    AuthorId INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
    Name NVARCHAR(50) NOT NULL,
    Surname NVARCHAR(50) NOT NULL,
)
GO

CREATE TABLE Books (
    BookId INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
    AuthorId INTEGER NOT NULL,
    Title NVARCHAR(50) NOT NULL,
    Amount INTEGER NOT NULL,
    Category NVARCHAR(50) NOT NULL,
    CONSTRAINT AuthorFK FOREIGN KEY(AuthorId) REFERENCES Authors(AuthorId)
)
GO

CREATE TABLE Borrows (
    BorrowId INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
    StudentId INTEGER NOT NULL,
    BookId INTEGER NOT NULL,
    TakenDate DATE NOT NULL,
    ReturnDate DATE,
    CONSTRAINT BookFK FOREIGN KEY(BookId) REFERENCES Books(BookId),
    CONSTRAINT StudentBorrowsFK FOREIGN KEY(StudentId) REFERENCES Students(StudentId)
)
